### ISSUE TITLE
Preserve residue numbers?

### ISSUE THREAD

**Issue by jchodera** [openmm/pdbfixer#105]
Does pdbfixer still not preserve residue numbers by default?

Is there a way we can change this behavior?

**Comment by jchodera** [comment]
I just realized this is a duplicate of #54

**Comment by jchodera** [comment]
Looks like the solution is to give the `keepIds=True` argument to `app.PDBFile.writeFile()`.

**Comment by jchodera** [comment]
Reopening because I am having trouble with `app.PDBFile.writeFile()`, receiving a `Fixed width overflow detected` error.  Will post more details in the OpenMM issue tracker.

**Comment by jiayeguo** [comment]
> Looks like the solution is to give the `keepIds=True` argument to `app.PDBFile.writeFile()`.

I need to retain the original PDB residue numbering in my case.   `keepIds=True` worked when using PDBFile.writeFile() but didn't seem suitable when using PDBFile() --- any comment on this?

**Comment by peastman** [comment]
What do you mean by "using PDBFile"?  How are you using it, if not calling `writeFile()`?

**Comment by jiayeguo** [comment]
I meant that when I loaded a pdb file using `PDBFile()` the residues are still renumbered in the Topology object.  It seems that the `keepIds=True` fix (to retain original numbering) is only on the output-file level and not the Topology-object level.
