### ISSUE TITLE
Is there a way to acetylate a protein using pdbfixer or modeller in openmm?

### ISSUE THREAD

**Issue by izaguirr** [openmm/pdbfixer#116]
I have generated an ensemble of random coils for folding simulations using RCG from 
U. Chicago. I am using amber99sb.xml and GB OBC. The structures RCG generates are not capped: neither acetylated (no ACE) nor NME. Is there a way to do this from within OpenMM or using pdbfixer? Thanks.
Apologies if this is not exactly an issue.

**Comment by peastman** [comment]
PdbFixer doesn't add ACE or NME groups to the ends, but it does add the necessary hydrogens and oxygens to terminate them properly.  Is that enough for your purposes, or do you specifically want ACE and NME?

**Comment by izaguirr** [comment]
Peter

Thanks, I was able to solve the problem. Best

Jesus

2016-01-25 16:56 GMT-05:00 peastman <notifications@github.com>:

**Comment by nitroamos** [comment]
#173
