### ISSUE TITLE
Strategies for adding protons to arbitrary components

### ISSUE THREAD

**Issue by jchodera** [openmm/pdbfixer#133]
@rafwiewiora pointed out that Amber's [`reduce`](http://kinemage.biochem.duke.edu/software/reduce.php) program has a nice solution to protonating arbitrary residues from the PDB. It uses a dictionary of all HET components in the PDB (presumably from the [Ligand Expo](http://ligand-expo.rcsb.org/) with definitions of protons for anything you might find in the PDB.

**Comment by swails** [comment]
It's not ours.  It's Michael Word's (he's in OpenEye, I think).  We just bundle it because we find it useful:

See here: http://kinemage.biochem.duke.edu/software/reduce.php

**Comment by peastman** [comment]
This was implemented in #295.
