### ISSUE TITLE
wrong when install under CENTOS7

### ISSUE THREAD

**Issue by guyujun** [openmm/pdbfixer#181]
error when install pdbfixer1.5 on centos7:
removing '/usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg
Extracting pdbfixer-1.5-py2.7.egg to /usr/lib/python2.7/site-packages
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
Sorry: TypeError: compile() expected string without null bytes
pdbfixer 1.5 is already the active version in easy-install.pth

pdbfixer is already can active by comline.
but it can not read PDB.

return another error..:
Traceback (most recent call last):
  File "./repair.py", line 107, in <module>
    repair(pdbfile)
  File "./repair.py", line 83, in repair
    fixer = PDBFixer(filename=pdbfile)
  File "/usr/lib/python2.7/site-packages/pdbfixer-1.5-py2.7.egg/pdbfixer/pdbfixer.py", line 277, in __init__
    templatePdb = app.PDBFile(os.path.join(templatesPath, file))
  File "/usr/lib64/python2.7/site-packages/simtk/openmm/app/pdbfile.py", line 160, in __init__
    self.positions = self._positions[0]
IndexError: list index out of range

please help.

**Comment by peastman** [comment]
How exactly did you install it?  Did you previously have another version installed?  It looks like it thinks you have two copies installed by two different means.

**Comment by awakenwu** [comment]
thank you， I install it by conda and it works well~
