### ISSUE TITLE
Make the addition of SEQRES residues optional

### ISSUE THREAD

**Issue by jiayeguo** [openmm/pdbfixer#182]
In a recent case `PDBFixer()` was trying to add ~40 residues (according to SEQRES) to the end of my protein; otherwise the OXT atom that's necessary at the end of the protein wouldn't be properly added.  Ways to get around this include modifying the `missingResidues` object to exclude residues you don't want or delete them afterwards.  It would be very considerate to let the user decide whether to add the additional SEQRES residues --- after all, adding a large portion (e.g. 40 residues) per se is very likely to cause other problems.

**Comment by peastman** [comment]
Modifying `missingResidues` is the correct way to handle this case.  The manual includes example code for exactly this situation.
