### ISSUE TITLE
How to select a model?

### ISSUE THREAD

**Issue by Ruibin-Liu** [openmm/pdbfixer#186]
It's stated explicitly that pdbfixer can 'Select a single position for atoms with multiple alternate positions listed', but I don't see an option to do that in the APIs. I followed the manual and used 2kul as an example. The output pdb file only contains the first model. I want to use the 10th model, but how?

**Comment by peastman** [comment]
Those are different things.  A single model can have alternate positions for particular atoms.  That's what it's talking about.  Separately from that, a file can contain multiple models, usually representing either a simulation trajectory or an ensemble of NMR models.  PDBFixer always just uses the first model.  If you want a different one, it's probably simplest to just create a file containing only the one model you want.
