### ISSUE TITLE
Which force field is used and how to change?

### ISSUE THREAD

**Issue by CryoSky** [openmm/pdbfixer#204]
Hi,
How can I check which force field is used in pdbfixer and how to change the force field to the one I want? I found the output of pdbfixer cannot pass the check of the standard charmm36 force field in both OpenMM and GROMACS.
Best,

**Comment by peastman** [comment]
What is the error you're getting?  The output is just a PDB file.  It isn't specific to one force field.

**Comment by CryoSky** [comment]
I have used a protein file with the Amber force field but it failed to load after the modification by pdbfixer. I have thought it change the name of some atoms but later fixed that I forget to add the ions force field together.
