### ISSUE TITLE
See our manual link broken

### ISSUE THREAD

**Issue by birbilis** [openmm/pdbfixer#212]
At the bottom of the pdbfixer repo page it says "See our manual" but when you follow the link there's some issue saying "TypeError: Failed to fetch" (the url is [http://htmlpreview.github.io/?https://raw.github.com/pandegroup/pdbfixer/master/Manual.html](http://htmlpreview.github.io/?https://raw.github.com/pandegroup/pdbfixer/master/Manual.html) )

**Comment by giadefa** [comment]
@jchodera this is still broken

**Comment by peastman** [comment]
Apparently this is a problem in htmlpreview: https://github.com/htmlpreview/htmlpreview.github.com/issues/95.  I posted about it a couple of weeks ago but haven't received any response.  I'll try again.

**Comment by TrianguloY** [comment]
Copied from the htmlpreview repo: the link is wrong, should be https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html (or https://htmlpreview.github.io/?https://github.com/pandegroup/pdbfixer/blob/master/Manual.html )

**Comment by TrianguloY** [comment]
Really? Can someone else try?
Here is what I see:
![imagen](https://user-images.githubusercontent.com/10616202/98577301-08b1d400-22bc-11eb-8a7d-d12bb8b745c1.png)

**Comment by peastman** [comment]
Very strange!  It fails for me in Firefox, but I just tried Safari and that works.  I thought maybe it had cached the bad version, but I tried clearing the cache in Firefox and it still fails.

**Comment by peastman** [comment]
Never mind: it was NoScript getting in the wey.

**Comment by birbilis** [comment]
note that page also points to the currently broken omnia.md url

**Comment by TrianguloY** [comment]
@birbilis I'm not a member of this repo, so its probably better to wait for an official reply, but my recommendation is to create a new issue for the broken omnia.md problem (its not related to this one) and, if you know of an alternate link, suggest it or even create a pull request with the change (like I did here).

**Comment by peastman** [comment]
The URL is correct, but that page is currently down.

**Comment by birbilis** [comment]
had mentioned it at https://github.com/openmm/openmm/issues/2896, hope they manage to grab that domain name back, else don't know in how many places they'll need to fix it (there is another url mentioned there that could be used)
