### ISSUE TITLE
After fixing my protein giving long tail 

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/pdbfixer#213]
I have fixed the structure named "2h6o" downloaded from the protein databank with the script given below with pdbfixer. But there was a long tail in the fixed structure (see the picture below). Putting this structure in a water box prolongs the MD calculation time (because of the box dimensions). What can I do? @peastman 

In the picture below, the raw and fixed structures are aligned.

![image](https://user-images.githubusercontent.com/57147948/97696965-66be0a80-1ab7-11eb-952e-89fb0dc02931.png)

```python
def fix_pdb(pdb_id):
    path = os.getcwd()
    if len(pdb_id) != 4:
        print("Creating PDBFixer...")
        fixer = PDBFixer(pdb_id)
        print("Finding missing residues...")
        fixer.findMissingResidues()
        print("Finding nonstandard residues...")
        fixer.findNonstandardResidues()
        print("Replacing nonstandard residues...")
        fixer.replaceNonstandardResidues()
        print("Removing heterogens...")
        fixer.removeHeterogens(keepWater=True)
        
        print("Finding missing atoms...")
        fixer.findMissingAtoms()
        print("Adding missing atoms...")
        fixer.addMissingAtoms()
        print("Adding missing hydrogens...")
        fixer.addMissingHydrogens(7)
        print("Writing PDB file...")

        PDBFile.writeFile(
            fixer.topology,
            fixer.positions,
            open(os.path.join(path, "%s_fixed_pH_%s.pdb" % (pdb_id.split('.')[0], 7)),
                 "w"),
            keepIds=True)
        return "%s_fixed_pH_%s.pdb" % (pdb_id.split('.')[0], 7)
```

**Comment by Bio-Otto** [comment]
@peastman I also owe you a special thank you. You are producing solutions to our problems very actively. Thank you so much for your precious time.

**Comment by peastman** [comment]
The manual contains an example of how to add missing residues only in the middle of chains, not at the ends:

https://github.com/openmm/pdbfixer/blob/b66bb54c0c53011470797e497bb91ac3cff5288c/Manual.html#L253-L263

**Comment by Bio-Otto** [comment]
@peastman thank you so much for clarifying.
