### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by Leo-Ryu** [openmm/pdbfixer#217]
Hello,

I’ve been working on a platform for editable codebase documentation and noticed this repo lacked documentation besides the manual. Would it be useful if I generated/hosted docs for this repo? 

The platform:
1) has a modern markdown editor to allow people to quickly and easily create new documents/user guides
2) is similar to readthedocs/sphinx in that reads through the codebase and builds/hosts linkable pages describing classes and functions, as well as their usages in the codebase. However unlike readthedocs/sphinx, it doesn't require any configuration to get up and running
3) tracks github repositories so that every build has the latest code

**Comment by peastman** [comment]
Thanks for the offer.  I think we'll stick to established platforms for our hosting.
