### ISSUE TITLE
addMissingAtoms() adds a linear chain of residues to protein termini in PDB ID 2a07

### ISSUE THREAD

**Issue by lancelot-droid** [openmm/pdbfixer#220]
Hello there!

I am trying to run PDBFixer on structure PDB ID 2a07 using the following commands:

from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
from pdbfixer.pdbfixer import PDBFixer

fixer = PDBFixer(pdbid='2a07')
fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.removeHeterogens(keepWater=False)
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(pH=7.0)

The output structure contains  several new residues, arranged in a linear chain, added to protein termini. I have traced the bug to addMissingAtoms() but cannot explain this behavior.

I welcome your guidance.

PS. You can compare the input (top image) and output (bottom image) structures below to see the linear chain of new residues added to the protein's termini.

![input](https://user-images.githubusercontent.com/7883257/119695424-00a62580-be03-11eb-8bf0-4cba4f54b39e.png)
![output](https://user-images.githubusercontent.com/7883257/119695443-069c0680-be03-11eb-9cb3-6d6d8e985ed8.png)

**Comment by peastman** [comment]
That means those residues are listed in the SEQRES section of the input file.  You tell it to add missing residues, so it does.  It has no idea what their conformation should be, so it just adds them sticking outward in a direction that won't clash with anything else.  When there are missing residues at the end of a chain, that often means they're flexible and couldn't be resolved in the electron density.

**Comment by lancelot-droid** [comment]
Thanks for clarifying. I was not aware of this until now. Is there a way to exclude these missing residues so that I can still run all-atom minimization?

**Comment by lancelot-droid** [comment]
Thanks for clarifying. I'll just download structures as PDB and filter out non ATOM and HETATM records.

**Comment by peastman** [comment]
See [the manual](https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html) for information about this.  If you don't want to add missing residues, remove the call to `findMissingResidues()` and replace it with

```python
fixer.missingResidues = {}
```

There's also an example that shows how to add missing residues in the middle of the chain but not at the ends.

**Comment by lancelot-droid** [comment]
Awesome. Thanks. I'll spend some more time with the manual.
