### ISSUE TITLE
PDBFixer not working some PDB file

### ISSUE THREAD

**Issue by AhmetGG** [openmm/pdbfixer#227]
Hi,

Before running Openmm, I would like to edit some protein structure via PDBFixer. But while Fixer read some PDB, some are not read. What can I do in order to be read PDB structure? By the way PDB structure is a predicted model not cystral.

**Comment by swails** [comment]
Without providing the PDB file that causes the problem there's really no way to diagnose.  If there's a PDB from RCSB that fails to parse, you can just provide the code.  Otherwise, can you attach it here so we can try to reproduce the problem?

**Comment by AhmetGG** [comment]
Thank you so much for replying.I added this unreaded file in the following:
[T1084.txt](https://github.com/openmm/pdbfixer/files/7100107/T1084.txt)
 I couldnt put this file as pdb so I can  put it as txt.

**Comment by peastman** [comment]
Your file begins with several lines that aren't part of the PDB format.

```
PFRMAT TS
TARGET T1084
MODEL 1
PARENT N/A
```

You need to remove those lines, or else prefix each one with "REMARK" to indicate that it's a comment.

**Comment by raoufkeskes** [comment]
for me it is not working and showing **KeyError: 'NDG'** 
the pdb code is : **3iyw**

**Comment by Zuricho** [comment]
> for me **fixer.addMissingAtoms()** it is not working and showing **KeyError: 'NDG'** the pdb code is : **3iyw**

I found a solution for your problem:

```
# replace nonstandard residues
fixer.findNonstandardResidues()
fixer.missingResidues = {}
fixer.replaceNonstandardResidues()
```

Set the missingResidues as blank, and continue with removeHeterogens will work.
