### ISSUE TITLE
User manual not updated

### ISSUE THREAD

**Issue by BJWiley233** [openmm/pdbfixer#238]
2 quick things for the [manual](https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html) :)

1) Need to update the order.  It's [%prog filename [options]](https://github.com/openmm/pdbfixer/blob/master/pdbfixer/pdbfixer.py#L1217) so manual needs to say:
```
Usage: pdbfixer
       pdbfixer filename [options] # change order in manual to this
```

2) Need to add `--verbose` option to manual

Thanks!
Brian

**Comment by peastman** [comment]
Thanks!
