### ISSUE TITLE
Version 1.8.1 fails to addSolvent() when boxShape kwarg is present. Also in openmm-setup

### ISSUE THREAD

**Issue by pguillem** [openmm/pdbfixer#249]
Hi guys.
I followed the instructions to install pdbfixer/flask/openmm via conda, later cloned openmm-setup from git.

When adding water (any box shape), an exception throws the message:
**TypeError: addSolvent() got an unexpected keyword argument 'boxShape'**

To reproduce, run:

```
wget https://files.rcsb.org/download/3OUX.pdb

python
import pdbfixer
fix = pdbfixer.PDBFixer("3OUX.pdb")
fix.addSolvent(boxSize=10, padding=1, boxShape="cube")
```

I get the exact same error if I use openmm-setup, right after selecting the Add Water option in the GUI.

"conda list" reports that pdbfixer version is 1.8.1.
Am I working with the correct version?

Thanks in advance
Pedro

**Comment by peastman** [comment]
You're using incompatible versions.  If you use the latest PDBFixer code from the repository, you also need to use the latest OpenMM code from the repository.  Alternatively you can install both of them with conda, which will give you the most recent release of each one.

**Comment by pguillem** [comment]
Thanks Peter. Will do.

Pedro
