### ISSUE TITLE
Which parameter set(periodicity, offset, k) does PeriodicTorsionForce use in soft.xml?

### ISSUE THREAD

**Issue by psp3dcg** [openmm/pdbfixer#250]
There are several parameter sets in some atom combinations of PeriodicTorsionForce, just like xml code below.
`  <Proper class1="N" class2="CT" class3="C" class4="N"  periodicity1="4" phase1="0" k1="0"  periodicity2="3" phase2="3.14159" k2="2.3012"  periodicity3="2" phase3="3.14159" k3="6.61072"  periodicity4="1" phase4="3.14159" k4="1.8828" />`
So, how does pdbfixer choose parameters when calculating PeriodicTorsionForce?

**Comment by psp3dcg** [comment]
> [This chapter](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html) in the OpenMM user guide describes how force fields work. It first matches templates to residues to select an atom type for each atom. Then it matches patterns like the one you quoted to select parameters.

Thank you for the quick and exact reply. After reading the chapter you mentioned, I still have two questions:
**First**, the Openmm user guide said "each torsion definition can specify multiple periodic torsion terms to add to its atoms." Are these parameter terms equivalent to each other when calculating torsion force?
**Second**, an improper torsion involves a central atom and three others that are bonded to it: atoms 2, 3, and 4 are all bonded to atom 1. I found two definations of the angle of improper dihedral when searching in browser.
(1) Consider four atoms i,j,k,l, among which j is linked covalently to i,l,k. The improper angle is defined as the angle between the (jl) line and the plane (ijk) [from here](https://faculty.uml.edu/vbarsegov/teaching/bioinformatics/lectures/ForceFieldModified.pdf)
(2) If the 4 atoms in an improper quadruplet (listed in the data file read by the [read_data](https://docs.lammps.org/read_data.html) command) are ordered I,J,K,L then  is the angle between the plane of I,J,K and the plane of J,K,L.[from here](https://docs.lammps.org/improper_harmonic.html)
How does the pdbfixer define the angle of improper dihedral?

**Comment by psp3dcg** [comment]
> an improper torsion involves a central atom and three others that are bonded to it: atoms 2, 3, and 4 are all bonded to atom 1.

OK, thank you for your help~:)

**Comment by peastman** [comment]
Did you intend to reopen this?  Was there something else you wanted clarification on?

**Comment by psp3dcg** [comment]
Recently I computed the Periodic Torsion Force of 4 atoms according to their true positions in PDB file, but some results seemed not closed to zero. Different with torsion force, Harmonic Bond Force and Angle Force results are almost zero when using true bond length and angle as input. 
If I take the true atom position as input, is it need to choose the parameter set(periodicity, offset, k) which make the minimum torsion force result , or it is still need to add all parameters to system?

**Comment by psp3dcg** [comment]
> Is there a reason you expect the force to be zero? Unless you energy minimized the structure, it will certainly not be at a minimum. And even if you minimize it, that doesn't mean every contribution to the force will independently be zero, only that the total force will be zero.

OK, I got it. Thank you for your answer, you are so nice~:)
