### ISSUE TITLE
Select residue atom positions for residues with alternate locations (altloc)

### ISSUE THREAD

**Issue by JSLJ23** [openmm/pdbfixer#253]
Hi developers of PDBfixer,

I was wondering, how do I select which one of the alternate locations (altloc) of a residue to retain in the fixed PDB?
For example in 3HYD (https://www.rcsb.org/structure/3HYD), GLU 3 has two possible positions A & B but PDB fixer by default only saves position A.
On the README, it is mentioned that PDBfixer can:

- Select a single position for atoms with multiple alternate positions listed.

However I am unable to find any information in the docs which might suggest how this could be done.
I am hoping to get some help here so raising this as an issue.

**Comment by peastman** [comment]
There's no option to select that.  It just uses the first one.  Do you have an application where it's important to specify a particular one?

**Comment by JSLJ23** [comment]
When PDB fixer selects these residue altlocs, does it do so based on highest occupancy or just the first occurrence?

**Comment by peastman** [comment]
It uses the first one in the file.
