### ISSUE TITLE
Failed to find missing residues in 6VYC

### ISSUE THREAD

**Issue by jw-feng** [openmm/pdbfixer#256]
Residues 680, 681, and 682 are missing from the A chain of PDB ID [6YVC](https://files.rcsb.org/view/6VYC.pdb). The SEQRES record contains GLY GLY ASP for those three residues, respectively. Using both the web interface and Python API, PDBFixer failed to find those missing residues. From looking at past issues, the culprit is likely a PDB formatting issue but I can't figure out how to fix it. Can you help?

**Comment by peastman** [comment]
Something's wrong with this file.  Compare the SEQRES records to the sequence found in the ATOM records.  They match up through residue 523, but then they become completely different.  Starting at residue 524, the sequence in the SEQRES records is ASP, PHE, SER... while the sequence in the ATOM records is PRO, GLY, ARG...

**Comment by jw-feng** [comment]
ASP PHE SER ALA PRO ASP ILE GLY SER LYS GLY MET ASN GLN VAL is part of the wild type sequence that was truncated in the crystallography construct.

**Comment by peastman** [comment]
One way or another, the file is internally inconsistent.  Either those residues should be absent in the SEQRES section, or else the residue numbers in the ATOM section should reflect that missing residues are being skipped.

Compare to residue 521 (SER) which is also missing.  In that case, the ATOM records skip from 520 to 522.

**Comment by jw-feng** [comment]
I manually edited the SEQRES records to delete that part of the WT sequence. What do you think about including helpful error messages to allow the user to debug? It would be more scalable than filing issues and having you personally answer them.

**Comment by peastman** [comment]
What kind of error message would be helpful?  It can tell you that the sequence didn't match, but without a complex analysis it usually is impossible to say why.

**Comment by jw-feng** [comment]
Tell me the sequence didn't match and print them out. It will give me a clue on where to look.
