### ISSUE TITLE
Missing b factors

### ISSUE THREAD

**Issue by zlcrrrr** [openmm/pdbfixer#266]
Hi, I noticed when using PDBFile.writeFile(fixer.topology, fixer.positions) to write a fixed PDB file, the b-factors are all set to be 0.0. Is there a way to preserve the original b-factors?

Thanks!

**Comment by peastman** [comment]
No, sorry.  The Topology class doesn't store b-factors.

**Comment by zlcrrrr** [comment]
Got it. Thanks!
