### ISSUE TITLE
[Unexpected behaviour] Unexpected behavoiur when parsing mmCIF files

### ISSUE THREAD

**Issue by Croydon-Brixton** [openmm/pdbfixer#269]
Thank you for providing pdbfixer.

I was using it to fix various protein structures and noticed the following unexpected behaviour (including the code to reproduce):
- The PDBFixer reports a different number of chains and chain names whether I load the same structure from a `.cif` or a `.pdb` file. 
- This doesn't happen for other parsers, for example the `biotite` parser. 

=> Does this suggest that `.cif` files might not parsed correctly wrt. to chain names? 

<img width="871" alt="Screenshot 2023-02-16 at 13 11 43" src="https://user-images.githubusercontent.com/19754061/219374059-f73a9766-e06e-4905-b3df-01f101b4d4ad.png">

Code to reproduce:
```python
from pdbfixer import PDBFixer

print("=== As loaded from CIF file ===")
fixer = PDBFixer(filename="2rb2.cif")
print("Chains:", [chain.id for chain in fixer.topology.chains()])
print(fixer.topology.atoms)

print("=== As loaded from PDB file ===")
fixer = PDBFixer(filename="2rb2.pdb")
print("Chains:", [chain.id for chain in fixer.topology.chains()])
print(fixer.topology.atoms)

print("==================================")
# As comparison parse with biotite:
import biotite.structure.io as bsio
import biotite.structure as bs

print(" === COMPARISON: Biotite from CIF ===")
biotite_from_cif = bsio.load_structure("2rb2.cif")
print(biotite_from_cif[:3], f"\nAtoms: {len(biotite_from_cif)}", f"\nChains: {bs.get_chains(biotite_from_cif)}")

print(" === COMPARISON: Biotite from PDB ===")
biotite_from_pdb = bsio.load_structure("2rb2.pdb")
print(biotite_from_pdb[:3], f"\nAtoms: {len(biotite_from_pdb)}", f"\nChains: {bs.get_chains(biotite_from_pdb)}")
```

**Comment by Croydon-Brixton** [comment]
EDIT: Looking further it seems the `.cif` files provide two chain IDs (`_atom_site.auth_asym_id ` and `_atom_site.label_asym_id `) and the PDBFixer parser has a different preference than the biotite parser.

Is there a way to change the default entry from which PDBFixer reads the chain_id such that it will match with that provided in PDB files?

**Comment by swails** [comment]
From [the code](https://github.com/openmm/openmm/blob/dd80fb3fdcba6a75803f8e68f444a657fe42d4f5/wrappers/python/openmm/app/pdbxfile.py#L99-L111), it seems that the `label_asym_id` and `auth_asym_id` columns are chosen based on which one specifies the "most" different chains.

However, the [`auth_asym_id`](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site.auth_asym_id.html) column is the one intended to align with what's found in the published literature (and, in my experience, the corresponding PDB file).  It is also a mandatory data item, so is guaranteed to always be in a (valid) PDBx/mmCIF file.

By contrast, I've found from recent investigation that the `_atom_site.label_*` fields are used primarily as internal relational keys between the different sections of the PDBx/mmCIF file (e.g., to map data between different sections, say anisotropic temperature factors to atoms).  For many "unimportant" atoms, like solvent and ions, it is not bothered to assign meaningful values to these atoms.

I personally think the OpenMM PDBx/mmCIF parser should stick to the `auth_*` fields where possible.

**Comment by Croydon-Brixton** [comment]
Thank you for the clarification @swails, this is very helpful. 

I agree with you that it would make sense for the default behaviour to stick to the `auth_*` fields when possible. 
In this case, it seems we would simply need to delete the [following lines](https://github.com/openmm/openmm/blob/dd80fb3fdcba6a75803f8e68f444a657fe42d4f5/wrappers/python/openmm/app/pdbxfile.py#L105-L111).

**Comment by peastman** [comment]
See #194 and #195.  We had to make it work that way because neither field consistently identifies chains in all files.

The presence of duplicate `auth_` and `label_` fields in PDBx/mmCIF is a mess that causes lots of problems.  They don't get used consistently in all files.  The documentation on them is ambiguous and sometimes contradictory.  It also sometimes conflicts with how they're used in files from RCSB.

**Comment by swails** [comment]
Interesting... that's too bad. :(
