### ISSUE TITLE
Is there any molecular dynamics or docking research published using pdbfixer?

### ISSUE THREAD

**Issue by RuikangSun** [openmm/pdbfixer#270]
Hi, I am a beginning user of openmm toolkit. I followed [this tutorial](https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html) and everything seems good. However, I am not sure if my results are reasonable. Is there any molecular dynamics or docking research published using pdbfixer? I want to refer to its protein preparation protocol made by pdbfixer. Thanks.

**Comment by trandinhquangloc** [comment]
Nice question, I also have the same question as yours due to several problems that I got when using PDBFixer (pdbfixer issue #201 - weird numbering and openmm issue #659 - cannot handle the system exceed 100,000 atoms as containing )

**Comment by peastman** [comment]
Those issues are intrinsic to the PDB format.  Try using PDBx/mmCIF instead, which can handle arbitrary numbers of atoms and residues.

**Comment by peastman** [comment]
On the more general question about protein preparation, PDBFixer is a useful tool but you shouldn't trust it.  There's a huge range of ways a PDB file could be messed up, and often no unique right solution.  PDBFixer tries to do something reasonable, but it's not magic.  There's no substitute for manually inspecting the result and making sure everything is ok.

**Comment by jamesmkrieger** [comment]
> Those issues are intrinsic to the PDB format. Try using PDBx/mmCIF instead, which can handle arbitrary numbers of atoms and residues.

There are several ways to overcome this such as using hexadecimal or hybrid36 for atom and residue numbers, which would be nice to have included. We have code for that in ProDy in case you want to look there

**Comment by peastman** [comment]
There are indeed several ways, which is the problem. :)  People have come up with various hacks to work around limitations of the spec, but all of them are necessarily nonstandard, and you can't rely on them working consistently between programs.  PDBx/mmCIF doesn't have that problem (though it introduces problems of its own).
