### ISSUE TITLE
PDBfixer with python=3.10 and openmm=7.7

### ISSUE THREAD

**Issue by matteo-cagiada** [openmm/pdbfixer#272]
Hi,
I'm trying to install pdbfixer on my colaboratory notebook, but due to the recent update to python 3.10 and the mandatory use of openmm>7.7 the pdbfixer library doesn't work anymore because some functions have changed their name. Is there any plan to release a new version compatible with the newest openmm? Thanks

**Comment by peastman** [comment]
The conda packages are now up.
