### ISSUE TITLE
pH protonation valid

### ISSUE THREAD

**Issue by groponp** [openmm/pdbfixer#278]
What happens is that I directly use this PDB in NAMD, but it gives me an error: "Warning: poorly guessed coordinate for atom HB1 SER:469 AP1." So, this is only resolved without selecting the hydrogens. I'm not really sure how to make the output of PDBfixer compatible with NAMD in such a way that if any residue is protonated, it is done correctly.

**Comment by peastman** [comment]
PDBFixer outputs the correct set of hydrogens for whatever pH you specify.  They should all be in reasonable positions, though you should always run some energy minimization on conformations before you try to simulate them.

I don't know what NAMD does or what its message means.  You need to ask the NAMD developers about that.
