### ISSUE TITLE
findMissingAtoms raises AttributeError if findMissingResidues has not been called first

### ISSUE THREAD

**Issue by nielskm** [openmm/pdbfixer#279]
The following code raises `AttributeError: 'PDBFixer' object has no attribute 'missingResidues'`:

```
from pdbfixer import PDBFixer
fixer = PDBFixer("6dyo.pdb")
fixer.findMissingAtoms()
```

Using the PDB from https://www.rcsb.org/structure/6DYO

**Comment by peastman** [comment]
See the instructions in [the manual](https://htmlpreview.github.io/?https://github.com/openmm/pdbfixer/blob/master/Manual.html).  Methods must be called in exactly the order shown.  Before you can call `findMissingAtoms()`, you first have to either call `findMissingResidues()` or else set the `missingResidues` field yourself.
