### ISSUE TITLE
Fixing out a very long chain with pdbfixer

### ISSUE THREAD

**Issue by stan1233** [openmm/pdbfixer#290]
```
    fixer = pdbfixer.PDBFixer(filename=str(input_pdb_file))
    fixer.removeHeterogens(keepWater=False)
    fixer.findMissingResidues()
    fixer.findNonstandardResidues()
    fixer.replaceNonstandardResidues()
    fixer.findMissingAtoms()
    fixer.addMissingAtoms(seed=seed)
    fixer.addMissingHydrogens(7.4)
```
When I use these codes to process `5FWS`, the processed protein appears with two very long chains. How should I deal with this situation?
![image](https://github.com/openmm/pdbfixer/assets/20401741/82eb591d-57b6-43a8-ba62-4b0fece3f458)

**Comment by peastman** [comment]
When the protein has terminal loops that weren't resolved in the crystal structure, PDBFixer doesn't try to do anything smart with them.  It just adds them pointing outward in a direction that is unlikely to clash with anything else.  If you run a short simulation, they should collapse inward fairly quickly.  But also consider whether you really want to include them in your simulation.  You have no information about their conformation.  It might be better to omit them.

Another possibility would be to start from [the structure predicted by AlphaFold](https://alphafold.ebi.ac.uk/entry/Q96MU8) for that protein.  It doesn't look a lot better though.  It just shows them as long flexible tails.

![image](https://github.com/openmm/pdbfixer/assets/4379786/86aa6817-58cd-422a-9b98-d36610d8c25c)
