### ISSUE TITLE
app.Modeller._loadStandardHydrogenDefinitions()  AttributeError: type object 'Modeller' has no attribute '_loadStandardHydrogenDefinitions'

### ISSUE THREAD

**Issue by MichaelAbel1** [openmm/pdbfixer#302]
![image](https://github.com/user-attachments/assets/c1dd30e2-59df-4700-ba34-0d75d1f5f38c)

![image](https://github.com/user-attachments/assets/770e6dc4-c803-43de-b73d-ccbc977b7d14)

**Comment by peastman** [comment]
You're using the latest unreleased source code for PDBFixer, which relies on unreleased changes in OpenMM.  You need to either use official releases of both packages, or install the latest development versions of both of them from source (not recommended for production work).

**Comment by MichaelAbel1** [comment]
Thanks, I was installing with pip before, but now ，I solved it with `conda install pdbfixer`.
