### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by kiyoon** [openmm/pdbfixer#311]
Running pdbfixer shows this warning:

```
  .../python3.12/site-packages/pdbfixer/pdbfixer.py:61: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import resource_filename
```

Using importlib should reduce the dependency of `setuptools` in runtime, and it's also available from old enough Python 3.7.

**Comment by peastman** [comment]
Thanks!  I removed it.  PDBFixer didn't even use that package.  It was only there for a doctest.
