### ISSUE TITLE
Have removeHeterogens() return the toDelete[] list?

### ISSUE THREAD

**Issue by Chance626** [openmm/pdbfixer#315]
Hello! I'm currently a graduate student at the Ohio State University in [John Herbert's lab](https://www.asc.ohio-state.edu/herbert.44/), and I am working on our group's [Fragmentation](https://gitlab.com/john-herbert-group/fragment) software package. I am working on creating a way for users to give a PDB ID and have our software automatically pull the protein, protonate it, and then run the calculations that are requested. I'm loving your implementation of PDBFixer over openmm and am find both quite useful! My current workflow is thus:

get PDB.pdb -> 'fix' the structure using PDBFixer -> add Hydrogens with openmm -> run calculations

During the 'fixing' step I am removing the heterogens (keepWater=True) because the ligands/metals/etc. don't play nice with the addHydrogens() function, and removing the heterogens seemed easier than adding in a list of rules for the atoms that throw errors. Eventually, after the hydrogens are added I want to add the heterogens back in (maybe allowing for ligand substitutions). Currently, I ripped your logic for the removeHeterogens() to get the toDelete[] list which I can then add back in to the final modeller.

I am new to collaborative software packages and github, and don't know the etiquette about fair use, etc. I think my implementation would be streamlined by having the removeHeterogens() function return the toDelete[] list, but don't know if this is a desired or breaking functionality of PDBFixer? Ideally, when installing the fragment software I'd like to include PDBFixer as a dependency. Is there a best practice for long term use of this? Can I make a branch and merge with the trunk if the changes are found suitable? Should I make a branch and have our software pull from that branch? Am I think of how to use PDBFixer/Openmm incorrectly?

Any tips or insight would be greatly appreciated!

**Comment by peastman** [comment]
That sounds like a good idea.  I'll make the change.  Thanks!

**Comment by Chance626** [comment]
Yay! Thank you for the speedy reply, much appreciated!!

**Comment by peastman** [comment]
The change is in #316.  Can you take a look and confirm it's doing what you want?

**Comment by Chance626** [comment]
Yes, that'd be perfect!

**Comment by peastman** [comment]
Thanks!
