### ISSUE TITLE
ACE ignored when calling addMissingHydrogens

### ISSUE THREAD

**Issue by ross-pure** [openmm/pdbfixer#319]
I was using this tool to add an ACE cap to my protein and then add missing hydrogens. I noticed that hydrogens were added to all residues except for the ACE. Looking at the code I believe I can see why this happens: when getting the variants for ACE, in the call to `_describeVariant`, there is the following logic
```python
if residue.name not in app.PDBFile._standardResidues and self._getTemplate(residue.name) is not None:
    # The user has registered a template for this residue.  Use the hydrogens from it.
    ...
```
This branch is taken because `ACE` is not in `_standardResidues`. But the template is just the default one loaded from the `templates` directory, which doesn't have any hydrogens. As a result, the value returned from `_describeVariant` is an empty list, instead of `None`. Consequently, since the `Modeller` has the following branch:
```python
if isinstance(variant, list):
    spec = Modeller._ResidueData(residue.name)
    infinity = float('Inf')
    spec.hydrogens = [Modeller._Hydrogen(name, parent, infinity, None, None) for name, parent in variant]
```
no hydrogens will be added.

My questions are:
- Is this expected behaviour?
- What is a reasonable work around to have the hydrogens actually get added to the ACE (and NME) residue(s)?

**Comment by peastman** [comment]
You're completely right.  We only want it to use user-supplied templates there, not ones from the templates directory.  That's what `residue.name not in app.PDBFile._standardResidues` is supposed to accomplish.  But really we should record a list of the built in templates and check that instead of `_standardResidues`.

**Comment by peastman** [comment]
The fix is in #320, if you want to test it out.

**Comment by ross-pure** [comment]
Just tested #320 on the system that I was having the issue with and now it seems to be fixed - Hs are added to the ACE. Thanks!

**Comment by peastman** [comment]
Thanks!
