### ISSUE TITLE
Atom name dialects

### ISSUE THREAD

**Issue by rmcgibbo** [openmm/pdbfixer#4]
I'm not sure if there is a canonical set of atom names, especially for hydrogens, but different codes have different expectations. For instance, when there are two hydrogens on the beta carbon, OpenMM will name them HB2 and HB3, whereas gromacs (eg pdb2gmx) will expect them to be named HB1 and HB2.

It would be a cool feature if when using pdbfixer, the user could optionally specify the "dialect" in which they want the output.

**Comment by BJWiley233** [comment]
Has gromacs still not switched to standard in almost 10 years since this post?

**Comment by peastman** [comment]
So far as I know, current Gromacs versions are intended to follow the standard.  If you find a case where it doesn't, you should report it to the developers since they would consider it a bug.

**Comment by BJWiley233** [comment]
That's weird since I installed from 2021.2 tar and the share tops are still the old/wrong atom names.  I will send email to them.  Thanks.

**Comment by BJWiley233** [comment]
I cannot seem to find the dictionary that indicates atom names HB2 & HB3 over HB1 and HB2 in the documentation.   The format of the website seem old :)

**Comment by BJWiley233** [comment]
I posted here https://gromacs.bioexcel.eu/t/pdb-3-0-standardized-atom-names-no-updated/4458.  Anyway to get someone at GROMACs to acknowledge?

**Comment by peastman** [comment]
>  Anyway to get someone at GROMACs to acknowledge?

No idea, sorry!
